"""model_artifact_job_id

Revision ID: 16211a6506bb
Revises: 145a3db2b015
Create Date: 2026-09-03 12:13:29.597010

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16211a6506bb"
down_revision: str | Sequence[str] | None = "145a3db2b015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Прочитано глазами. Колонка nullable намеренно: артефакты, обученные
    # до неё, своей задачи не знают, и выдумать её нечем. NOT NULL
    # потребовал бы либо значения по умолчанию (то есть вымышленной задачи
    # у настоящей модели), либо удаления прежних моделей — а модель, за
    # которой стоит чей-то счёт, дороже опрятной схемы.
    #
    # Уникальность по job_id держит «одна задача — одна модель». NULL
    # с NULL в PostgreSQL не конфликтует, поэтому старые артефакты
    # уникальности не мешают.
    #
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_artifacts", sa.Column("job_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_model_artifacts_job_id", "model_artifacts", ["job_id"], unique=True
    )
    op.create_foreign_key(
        op.f("fk_model_artifacts_job_id_jobs"),
        "model_artifacts",
        "jobs",
        ["job_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Откат ДЕСТРУКТИВЕН по одной колонке: связь модели с задачей, которая
    # её обучила, пропадает безвозвратно. Сами модели остаются, и повторное
    # обучение заведёт связь заново — но старые артефакты после отката и
    # повторного наката останутся без job_id навсегда.
    #
    # Круг upgrade → downgrade base → upgrade проверен. Типов enum здесь
    # нет — удалять в downgrade нечего, кроме перечисленного ниже.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_model_artifacts_job_id_jobs"), "model_artifacts", type_="foreignkey"
    )
    op.drop_index("ix_model_artifacts_job_id", table_name="model_artifacts")
    op.drop_column("model_artifacts", "job_id")
    # ### end Alembic commands ###
